---
- hosts: all
  vars:
#    ansible_user: "administrator"
#    ansible_password: "mypassword"
    ansible_port: 22
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_ssh_retries: 3
#    ansible_shell_type: powershell
#    ansible_shell_type: cmd
#    ansible_become_method: runas
#    ansible_become_user: "{{ ansible_user }}"
 
 tasks:
    - name: Check if /etc directory exists
      stat:
        path: /etc
      register: result

    - name: Print result
      debug:
        msg: "/etc directory exists"
      when: result.stat.isdir
