---

- hosts: all
  become: yes
  become_user: mint
  become_method: sudo
  vars:
     ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  tasks:

    - name: create share directory
      file:
        path: /tmp/share
        state: directory


    - name: mount
      mount:
        path: /tmp/share
        src: //192.168.1.19/winimages
        fstype: cifs
        opts: 'username=test,password=test'
        state: mounted

