---
- hosts: all
  vars:
    ansible_port: 22
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_ssh_retries: 3
 
  tasks:

    - name: Get Bluetooth MAC address in linux hosts
      shell: hciconfig | grep -i address | awk '{print $3}'
      register: bluetooth_mac_address
      ignore_errors: yes

    - name: Show Bluetooth MAC address
      debug:
        msg: "{{ bluetooth_mac_address.stdout_lines }}"    


    - name: Get MAC Addresses
#      debug: msg="{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"
#      debug: msg="{{ hostvars[inventory_hostname] }}"
      debug:
        msg: "{{ ansible_interfaces | difference(['lo']) | map('regex_replace', '^(.*)$', 'ansible_\\1' ) | map('extract', hostvars[inventory_hostname], 'macaddress')  | list }}"
